- name: Update packages
  become: yes
  apt:
    update_cache: yes

- name: Upgrade packages
  become: yes
  apt:
    upgrade: safe

- name: Install Node Version Manager
  become: yes
  git: repo=https://github.com/creationix/nvm.git dest=/root/.nvm version=v0.38.0
  tags: nvm

- name: Install node and set version
  become: yes
  become_user: root
  shell: |
    source /root/.nvm/nvm.sh
    nvm install 13.14.0
    nvm use default 13.14.0
  args:
    executable: /bin/bash

- name: Install pm2
  become: yes
  become_user: root
  shell: |
    source /root/.bashrc
    nvm use 13.14.0
    npm install -g pm2
  args:
    executable: /bin/bash

- name: Export environment config
  become: yes
  become_user: root
  shell: |
    cat .env >> /root/.bashrc
