- name: Update packages
  become: yes
  apt:
    update_cache: yes

- name: Upgrade packages
  apt:
    upgrade: yes

- name: Install Node Version Manager
  become: yes
  git: repo=https://github.com/creationix/nvm.git dest=/root/.nvm version=v0.38.0
  tags: nvm

- name: Install node and set version
  become: yes
  become_user: root
  shell: . /root/.nvm/nvm.sh && nvm install 13.14.0

- name: Install pm2
  become: yes
  shell: npm install -g pm2

- name: Export environment config
  become: yes
  shell: |
    cat .env >> ~/.bashrc
    ~/.bashrc
