- name: Update packages
  become: yes
  apt:
    update_cache: yes

- name: Upgrade packages
  become: yes
  apt:
    upgrade: safe

- name: Copy .env file
  copy:
    src: .env
    dest: /home/ubuntu/.env

- name: Export environment config
  become: yes
  become_user: root
  shell: |
    cat /home/ubuntu/.env >> /root/.bashrc

- name: Reload bash
  become: yes
  become_user: root
  shell: . /root/.bashrc

- name: Copy project files
  copy:
    src: backend/
    dest: /home/ubuntu/backend/

- name: Install dependencies
  become: true
  shell: |
    cd /home/ubuntu/backend
    npm install

- name: Build project
  become: true
  shell: |
    cd /home/ubuntu/backend
    npm run build

- name: Stop all previous instances
  become: yes
  shell: pm2 stop all || return 0

- name: Delete all previous instances
  become: yes
  shell: pm2 delete all || return 0

- name: Start server
  become: yes
  shell: pm2 start /home/ubuntu/backend/dist/main.js
