- name: Update packages
  become: yes
  apt:
    update_cache: yes

- name: Upgrade packages
  become: yes
  apt:
    upgrade: safe

- name: Copy project files
  copy:
    src: backend/
    dest: /home/ubuntu/backend/

- name: Copy .env file
  copy:
    src: .env
    dest: /home/ubuntu/backend/.env

- name: Install dependencies
  become: true
  shell: |
    cd /home/ubuntu/backend
    npm install

- name: Build project
  become: true
  shell: |
    cd /home/ubuntu/backend
    npm run build
