Description: >
  UdaPeople backend stack.

Parameters:
  ID:
    Description: Unique identifier.
    Type: String
  ImageID:
    Description: The Amazon Image ID that will be used to provision the instance.
    Type: String
  KeyName:
    Description: The key pair name that will be used to authenticate into this machine.
    Type: String
  SSHCidrIp:
    Description: Range of IP addresses allowed to SSH into the instance.
    Type: String
  WebCidrIp:
    Description: Range of IP addresses allowed to send requests to the web API.
    Type: String
  DatabaseUsername:
    Description: Database's master username
    Type: String
  DatabasePassword:
    Description: Database's master password
    Type: String

Resources:
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub UdaPeople-${ID}
      GroupDescription: Allow port 22 and port 3030.
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref SSHCidrIp
        - IpProtocol: tcp
          FromPort: 3030
          ToPort: 3030
          CidrIp: !Ref WebCidrIp

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      SecurityGroups:
        - Ref: InstanceSecurityGroup
      KeyName: !Ref KeyName
      ImageId: !Ref ImageID
      Tags:
        - Key: Name
          Value: !Sub backend-${ID}

  RDSDatabase:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 20
      DBInstanceClass: db.t2.micro
      DBName: udagram
      Engine: postgres
      MasterUsername: !Ref DatabaseUsername
      MasterUserPassword: !Ref DatabasePassword
