AWSTemplateFormatVersion: 2010-09-09

Description: >
  UdaPeople database stack.

Parameters:
  DatabaseUsername:
    Description: Database's master username
    Type: String
  DatabasePassword:
    Description: Database's master password
    Type: String

Resources:
  RDSDatabase:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 20
      DBInstanceClass: db.t2.micro
      DBName: udapeople
      Engine: postgres
      MasterUsername: !Ref DatabaseUsername
      MasterUserPassword: !Ref DatabasePassword
      PubliclyAccessible: true

Outputs:
  DatabaseHost:
    Value: !GetAtt RDSDatabase.Endpoint.Address
    Description: The database host address
    Export:
      Name: DatabaseHost
  DatabasePort:
    Value: !GetAtt RDSDatabase.Endpoint.Port
    Description: The database port
    Export:
      Name: DatabasePort
